### ISSUE TITLE
writeln support

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32f3xx-hal#106]
It would be nice to have support for writeln!  ( which comes with "use core::fmt::Write;" ). I think this is done in  stm32f1xx-hal and  stm32f4xx-hal by implementing a trait.  I'm a newbie, so probably wrong about how it is done, but I do know it works with those two hals and not with stmf3xx-hal.

**Comment by ra-kete** [comment]
Looks like they simply implement `core::fmt::Write` for their serial tx type: https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/serial.rs#L1763

We have such a type as well, just implemented inside a macro (`Tx<$USARTX>`). It should be very easy to impl `Write` for it too.
