### ISSUE TITLE
Wrong alternate function mappings for GPIO banks

### ISSUE THREAD

**Issue by Sh3Rm4n** [stm32-rs/stm32f3xx-hal#118]
As discussed in https://github.com/stm32-rs/stm32f3xx-hal/pull/116#discussion_r456950850, the alternate function mapping for the gpios are not 100 % according to the [device datasheets (p.43) ](https://www.st.com/resource/en/datasheet/stm32f373cc.pdf), in which the alternate function table is listed. 

https://github.com/stm32-rs/stm32f3xx-hal/blob/2ea16b4488721f1a2db61fb5119320f04e39b33f/src/gpio.rs#L921-L930

**Comment by ra-kete** [comment]
With #129 merged, this *should* be fixed now. I'm closing this issue. If anyone finds specific instances of wrong mappings we can reopen again.
