### ISSUE TITLE
Why are the ppre1 and ppre2 methods internal?

### ISSUE THREAD

**Issue by wbuck** [stm32-rs/stm32f3xx-hal#193]
Having access to the `PPRE1` & `PPRE2` bits of the `RCC_CFGR` register could be really helpful when performing frequency calculations.

I see that on the `impl` of the [Clocks](https://github.com/stm32-rs/stm32f3xx-hal/blob/master/src/rcc.rs#L790-L798) struct the following 2 `internal` methods:

    pub(crate) fn ppre1(&self) -> u8 {
        self.ppre1
    }

    // TODO remove `allow`
    #[allow(dead_code)]
    pub(crate) fn ppre2(&self) -> u8 {
        self.ppre2
    }

Is there any reason why these are `internal`? 
Like I mentioned above they would be helpful when calculating a peripherals clock frequency.

**Comment by Sh3Rm4n** [comment]
No particular reason, as far as I know. These could be made public, I guess. Thanks for the suggestion.
