### ISSUE TITLE
I2C doesn't work with repeating starts

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32f3xx-hal#197]
This is part of the spec, and is required by some devices. Fixed [in this PR](https://github.com/stm32-rs/stm32f3xx-hal/pull/166). Copy+pasted `write_read` method from the H7 HAL.

Pre-fix: https://i.imgur.com/wONAYTl.png
Post-fix: https://i.imgur.com/8NhBxVk.png

Note the `Sr` (Repeating start) flag towards the left on the fixed one, replacing the `P` `S` (Stop, start) on the current impl. And note the correct data on the fix towards the right, compared to 0xFF.

Per the [Embedded Hal docs](https://docs.rs/embedded-hal/0.2.4/embedded_hal/blocking/i2c/trait.WriteRead.html), this is how `WriteRead` is expected to behave.

**Comment by eldruin** [comment]
Just weighing in here to point to the I2C specification corroborating this. See: [Figure 13 in section 3.1.10 of UM10204](https://www.nxp.com/docs/en/user-guide/UM10204.pdf#G1656228).

**Comment by Piroro-hs** [comment]
I tested on stm32f303x8 and can't reproduce the issue...

**Comment by David-OConnor** [comment]
What device did you test with? I2C works on many devices as-is, but the current non-compliant implementation fails on others. This brings it closer to I2C standards. (There's still a problem of Nacking at the end I haven't solved)

**Comment by Piroro-hs** [comment]
According to [section 3.1.10](https://www.nxp.com/docs/en/user-guide/UM10204.pdf#G1656228), Master-receiver Nacking at the end is a spec compliant behavior.
