### ISSUE TITLE
Should `Gpiox` be marked `Send`?

### ISSUE THREAD

**Issue by russellmcc** [stm32-rs/stm32f3xx-hal#249]
I'm using the erased `PXx` types so I can store pins from multiple ports into a single array.  I noticed `Gpiox` uses a pointer, so it does not implement `Send`.  However, it looks like we only ever do atomic or side-effect free operations on this pointer - does that mean `Send` (or even `Sync`) would be appropriate to implement?  

I'm not enough of an expert on unsafe rust to know for sure, but according to my reading of [the rustonomicon](https://doc.rust-lang.org/nomicon/send-and-sync.html) this would be allowed.

**Comment by Sh3Rm4n** [comment]
Seems reasonable. I guess  `PXx` should implement `Send` otherwise it is a flaw in there design. Because if the pointer it is not automatically implemented. 

So if it is safe to do so, why not?
