### ISSUE TITLE
Missing `MosiPin` implementation?

### ISSUE THREAD

**Issue by hallgchris** [stm32-rs/stm32f3xx-hal#320]
Hi all, quick issue here.

I'm upgrading a project from a previous version of the crate (`0.7.0`) to the latest (`0.9.0`), running on a `STM32F303K8T6`. My project uses `SPI1` with `PB5` as `MOSI`.

The `impl` for this pin [was present in 0.7.0](https://github.com/stm32-rs/stm32f3xx-hal/blob/66c0d21ae19ae0bee09ec834a6c9c90b2191e17d/src/spi.rs#L343) but appears to be no longer present on `master`. The datasheet says that SPI1 MOSI should be an alternate function for PB7:
![image](https://user-images.githubusercontent.com/17876556/179382638-4c2736ca-d315-4ad7-998f-e0c55ebf005c.png)

Is this unintentional, or otherwise, what am I missing? The SPI was working on the older version.

Thanks!

**Comment by Sh3Rm4n** [comment]
Between `0.7` and 0.9` was much refactoring regarding SPI, so it could be that it has been accidentally removed. 

If the datasheet says, that it should exist, then this is definitely a bug. 

Thanks for the report!
