### ISSUE TITLE
Add stm32f3 support to probe-rs

### ISSUE THREAD

**Issue by dfrankland** [stm32-rs/stm32f3xx-hal#49]
Would be great to have some examples and docs on using this crate with [`probe-rs`](https://github.com/probe-rs/probe-rs) once there is support for it.

**Comment by Sh3Rm4n** [comment]
Current master of probe-rs does support stm32f3 🎉 

Ref https://github.com/probe-rs/probe-rs/pull/211

**Comment by dfrankland** [comment]
Amazing!
