### ISSUE TITLE
Support for DACs

### ISSUE THREAD

**Issue by dfrankland** [stm32-rs/stm32f3xx-hal#51]
I just got a little speaker to test with, so I thought it might be nice to get started on support for DACs.

Example here:
https://github.com/stm32-rs/stm32f0xx-hal/pull/70

**Comment by strom-und-spiele** [comment]
Gist for direct usage:
https://gist.github.com/strom-und-spiele/8155f19258adfd66214d2d0aac956a43

**Comment by David-OConnor** [comment]
https://github.com/stm32-rs/stm32f3xx-hal/pull/133

**Comment by Sh3Rm4n** [comment]
#318 implemented a minimal DAC driver
