### ISSUE TITLE
Update to PAC crate stm32f3 version 0.7.x

### ISSUE THREAD

**Issue by tkeksa** [stm32-rs/stm32f3xx-hal#7]
Do you plan to update to PAC crate stm32f3 version 0.7.x?

**Comment by dfrankland** [comment]
Yep! I was working on it a week or so ago, but ran out of time to fix a few things. Hopefully, I can get back to it this weekend. If anyone else beats me to the punch, I’ll gladly review and merge.

**Comment by tkeksa** [comment]
Thanks! Let me know if I could anything review or test so as to help you.
