### ISSUE TITLE
Update embedded-hal to v0.2.3

### ISSUE THREAD

**Issue by ibutra** [stm32-rs/stm32f3xx-hal#8]
Hi,

are you planning on updating to embedded-hal v0.2.3? Especially implement the new digital::v2 traits?
Or would you be willing to accept a pull request for it?

**Comment by dfrankland** [comment]
Yep! I was working on it a week or so ago, but ran out of time to fix a few things. Hopefully, I can get back to it this weekend. I will happily review and merge any PRs made for this though 👍
