### ISSUE TITLE
Can't clear a UART read error

### ISSUE THREAD

**Issue by thejpster** [stm32-rs/stm32f3xx-hal#90]
If I get a UART Error::Overrun, that bit seems to be sticky and won't go away. Could we add a clear function so we can clear that bit? Or could we clear the bit automatically when we return the error?

**Comment by thejpster** [comment]
![image](https://user-images.githubusercontent.com/959887/78912360-67da0c80-7a7f-11ea-9c74-7115ec53cdeb.png)

**Comment by thejpster** [comment]
See #91

**Comment by Sh3Rm4n** [comment]
Closed by #91
